# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Training Course on Next generation sequencing
tagline:             Training Course on Next generation sequencing
description:         NGS base training
url:                 'https://bioinfo-dirty-jobs.github.io/Thebasics/'
baseurl:             ''
twitter_username:
github_username:  bioinfo-dirty-jobs
pages_url: https://bioinfo-dirty-jobs.github.io/Thebasics
github_url: https://bioinfo-dirty-jobs.github.io/Thebasics

# Custom vars
version:             3.0

# Build settings
markdown: kramdown
